import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        heading: ["var(--font-heading)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "monospace"],
      },
      colors: {
        aistroyka: {
          accent: "var(--aistroyka-accent)",
          "accent-hover": "var(--aistroyka-accent-hover)",
          "accent-pressed": "var(--aistroyka-accent-pressed)",
          "accent-disabled": "var(--aistroyka-accent-disabled)",
          "accent-light": "var(--aistroyka-accent-light)",
          "bg-branded": "var(--aistroyka-bg-branded)",
          "bg-branded-surface": "var(--aistroyka-bg-branded-surface)",
          "bg-primary": "var(--aistroyka-bg-primary)",
          "bg-secondary": "var(--aistroyka-bg-secondary)",
          surface: "var(--aistroyka-surface)",
          "surface-raised": "var(--aistroyka-surface-raised)",
          "surface-muted": "var(--aistroyka-surface-muted)",
          "text-primary": "var(--aistroyka-text-primary)",
          "text-secondary": "var(--aistroyka-text-secondary)",
          "text-tertiary": "var(--aistroyka-text-tertiary)",
          "text-inverse": "var(--aistroyka-text-inverse)",
          "text-on-branded": "var(--aistroyka-text-on-branded)",
          success: "var(--aistroyka-success)",
          warning: "var(--aistroyka-warning)",
          error: "var(--aistroyka-error)",
          info: "var(--aistroyka-info)",
          "border-subtle": "var(--aistroyka-border-subtle)",
          "border-strong": "var(--aistroyka-border-strong)",
        },
      },
      borderRadius: {
        "aistroyka-xs": "var(--aistroyka-radius-xs)",
        "aistroyka-sm": "var(--aistroyka-radius-sm)",
        "aistroyka-md": "var(--aistroyka-radius-md)",
        "aistroyka-lg": "var(--aistroyka-radius-lg)",
        "aistroyka-xl": "var(--aistroyka-radius-xl)",
        "aistroyka-xxl": "var(--aistroyka-radius-xxl)",
        "aistroyka-card": "var(--aistroyka-radius-card)",
        card: "var(--aistroyka-radius-card)",
        "card-sm": "var(--aistroyka-radius-lg)",
        "card-lg": "var(--aistroyka-radius-xxl)",
      },
      boxShadow: {
        "aistroyka-e1": "var(--aistroyka-shadow-e1)",
        "aistroyka-e2": "var(--aistroyka-shadow-e2)",
        "aistroyka-e3": "var(--aistroyka-shadow-e3)",
        "aistroyka-e4": "var(--aistroyka-shadow-e4)",
        card: "var(--aistroyka-shadow-e1)",
        "card-elevated": "var(--aistroyka-shadow-e2)",
      },
      spacing: {
        "aistroyka-1": "var(--aistroyka-space-1)",
        "aistroyka-2": "var(--aistroyka-space-2)",
        "aistroyka-3": "var(--aistroyka-space-3)",
        "aistroyka-4": "var(--aistroyka-space-4)",
        "aistroyka-5": "var(--aistroyka-space-5)",
        "aistroyka-6": "var(--aistroyka-space-6)",
        "aistroyka-8": "var(--aistroyka-space-8)",
        "aistroyka-10": "var(--aistroyka-space-10)",
        "aistroyka-12": "var(--aistroyka-space-12)",
        "aistroyka-touch": "var(--aistroyka-touch-min)",
      },
      minHeight: {
        "aistroyka-touch": "var(--aistroyka-touch-min)",
      },
      minWidth: {
        "aistroyka-touch": "var(--aistroyka-touch-min)",
      },
      width: {
        "aistroyka-empty-icon": "var(--aistroyka-empty-icon)",
        "aistroyka-empty-icon-sm": "var(--aistroyka-empty-icon-sm)",
      },
      height: {
        "aistroyka-empty-icon": "var(--aistroyka-empty-icon)",
        "aistroyka-empty-icon-sm": "var(--aistroyka-empty-icon-sm)",
      },
      transitionDuration: {
        "aistroyka-instant": "var(--aistroyka-duration-instant)",
        "aistroyka-fast": "var(--aistroyka-duration-fast)",
        "aistroyka-normal": "var(--aistroyka-duration-normal)",
        "aistroyka-slow": "var(--aistroyka-duration-slow)",
        "aistroyka-button": "var(--aistroyka-duration-button)",
      },
      fontSize: {
        "aistroyka-large": "var(--aistroyka-font-large)",
        "aistroyka-title": "var(--aistroyka-font-title)",
        "aistroyka-title2": "var(--aistroyka-font-title2)",
        "aistroyka-title3": "var(--aistroyka-font-title3)",
        "aistroyka-headline": "var(--aistroyka-font-headline)",
        "aistroyka-body": "var(--aistroyka-font-body)",
        "aistroyka-callout": "var(--aistroyka-font-callout)",
        "aistroyka-subheadline": "var(--aistroyka-font-subheadline)",
        "aistroyka-footnote": "var(--aistroyka-font-footnote)",
        "aistroyka-caption": "var(--aistroyka-font-caption)",
        "aistroyka-caption2": "var(--aistroyka-font-caption2)",
      },
    },
  },
  plugins: [],
};
export default config;
