import type {
  RomaTestCatalog,
  RomaTestCatalogDomain,
  RomaTestCatalogItem,
  RomaTestCatalogPlatform,
  RomaTestCatalogRole,
  RomaTestCatalogSummary,
} from "./roma-test-catalog.types";

type ItemInput = Omit<RomaTestCatalogItem, "enabled">;

function t(partial: ItemInput): RomaTestCatalogItem {
  return { ...partial, enabled: false };
}

const ITEMS: RomaTestCatalogItem[] = [
  // WEB
  t({
    testId: "web-routing-locale-default",
    title: "Locale routing default",
    description: "Verify default locale redirect and valid locale segments on public and dashboard entry.",
    domain: "web",
    category: "routing",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["anonymous", "tenant_admin"],
    requiredEvidence: ["route_status", "final_url"],
    affectedModules: ["middleware", "i18n"],
    relatedGraphNodes: ["pa-public-website", "pa-web-dashboard", "td-web-e2e"],
    releaseCritical: true,
    estimatedRuntime: "2m",
    prerequisites: ["staging deploy current"],
    outputs: ["pass_fail", "screenshot_optional"],
    maturity: "defined",
  }),
  t({
    testId: "web-routing-platform-admin-guard",
    title: "Platform admin route guard",
    description: "Unauthenticated platform-admin paths redirect to login; tenant /admin does not grant platform access.",
    domain: "web",
    category: "routing",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["anonymous", "tenant_admin", "platform_owner"],
    requiredEvidence: ["http_status", "redirect_target"],
    affectedModules: ["platform-admin", "middleware"],
    relatedGraphNodes: ["pa-platform-admin", "td-security-rbac", "risk-platform-admin-exposure"],
    releaseCritical: true,
    estimatedRuntime: "3m",
    prerequisites: ["test credentials for tenant admin and platform owner"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "web-forms-login-validation",
    title: "Login form validation",
    description: "Login/register forms show validation errors and successful auth redirects to expected dashboard.",
    domain: "web",
    category: "forms",
    priority: "p0",
    severity: "high",
    executionType: "automated",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["form_errors", "post_auth_url"],
    affectedModules: ["auth", "dashboard"],
    relatedGraphNodes: ["pa-authentication", "api-auth-session", "td-web-e2e"],
    releaseCritical: true,
    estimatedRuntime: "4m",
    prerequisites: ["E2E_USER_EMAIL/PASSWORD or pilot creds"],
    outputs: ["pass_fail"],
    maturity: "partial",
  }),
  t({
    testId: "web-i18n-message-parity",
    title: "Locale message parity",
    description: "en/ru/es/it bundles aligned for dashboard and activation scopes via i18n:check.",
    domain: "web",
    category: "localization",
    priority: "p1",
    severity: "medium",
    executionType: "automated",
    supportedPlatforms: ["web"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["i18n_check_exit_code"],
    affectedModules: ["i18n", "dashboard"],
    relatedGraphNodes: ["pa-web-dashboard", "td-web-e2e"],
    releaseCritical: false,
    estimatedRuntime: "1m",
    prerequisites: ["bun run i18n:check"],
    outputs: ["pass_fail", "missing_keys_report"],
    maturity: "live",
  }),
  t({
    testId: "web-responsive-dashboard-shell",
    title: "Dashboard responsive shell",
    description: "Dashboard navigation and primary layouts usable at mobile and desktop breakpoints.",
    domain: "web",
    category: "responsive",
    priority: "p2",
    severity: "medium",
    executionType: "manual",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["tenant_admin", "manager"],
    requiredEvidence: ["viewport_screenshots"],
    affectedModules: ["dashboard"],
    relatedGraphNodes: ["pa-web-dashboard", "td-web-e2e"],
    releaseCritical: false,
    estimatedRuntime: "15m",
    prerequisites: ["browser devtools or Playwright viewports"],
    outputs: ["manual_checklist"],
    maturity: "planned",
  }),
  t({
    testId: "web-browser-compat-public",
    title: "Public site browser compatibility",
    description: "Public homepage and cabinet CTA render in Chromium, Safari, and Firefox baseline.",
    domain: "web",
    category: "browser_compatibility",
    priority: "p2",
    severity: "low",
    executionType: "manual",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["browser_matrix_notes"],
    affectedModules: ["public-site"],
    relatedGraphNodes: ["pa-public-website", "td-web-e2e"],
    releaseCritical: false,
    estimatedRuntime: "20m",
    prerequisites: ["target browsers installed"],
    outputs: ["manual_matrix"],
    maturity: "planned",
  }),

  // BACKEND
  t({
    testId: "backend-api-health",
    title: "Health API contract",
    description: "GET /api/v1/health returns 200 with buildStamp on staging/production.",
    domain: "backend",
    category: "apis",
    priority: "p0",
    severity: "critical",
    executionType: "probe",
    supportedPlatforms: ["api", "staging", "production"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["http_200", "buildStamp_sha7"],
    affectedModules: ["api", "deploy"],
    relatedGraphNodes: ["api-health", "pa-release-pipeline", "td-release-smoke", "rg-staging-deploy"],
    releaseCritical: true,
    estimatedRuntime: "30s",
    prerequisites: ["BASE_URL set"],
    outputs: ["json_response"],
    maturity: "live",
  }),
  t({
    testId: "backend-api-auth-session",
    title: "Auth session API boundary",
    description: "Protected /api/v1/* routes reject unauthenticated requests with correct status.",
    domain: "backend",
    category: "auth",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["401_or_403", "no_data_leak"],
    affectedModules: ["api", "auth"],
    relatedGraphNodes: ["api-auth-session", "pa-authentication", "risk-auth-broken"],
    releaseCritical: true,
    estimatedRuntime: "2m",
    prerequisites: ["staging API reachable"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "backend-api-reports-crud",
    title: "Reports API contract",
    description: "Report sync endpoints accept worker payloads and enforce tenant scope.",
    domain: "backend",
    category: "apis",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["worker", "manager"],
    requiredEvidence: ["201_or_200", "tenant_scoped_row"],
    affectedModules: ["reports", "api"],
    relatedGraphNodes: ["api-reports", "pa-worker-reports", "td-backend-api"],
    releaseCritical: true,
    estimatedRuntime: "5m",
    prerequisites: ["worker test user", "project fixture"],
    outputs: ["pass_fail", "response_body"],
    maturity: "defined",
  }),
  t({
    testId: "backend-storage-upload",
    title: "Storage upload API",
    description: "Upload endpoints store files and return signed URLs under tenant policy.",
    domain: "backend",
    category: "storage",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["worker", "tenant_admin"],
    requiredEvidence: ["upload_success", "retrieval_ok"],
    affectedModules: ["storage", "upload"],
    relatedGraphNodes: ["api-upload-storage", "infra-supabase-storage", "risk-storage-unavailable"],
    releaseCritical: true,
    estimatedRuntime: "4m",
    prerequisites: ["storage bucket configured"],
    outputs: ["pass_fail", "object_key"],
    maturity: "defined",
  }),
  t({
    testId: "backend-jobs-cron-gate",
    title: "Jobs/cron owner gate",
    description: "Cross-tenant cron and global job triggers require platform owner — tenant admin blocked.",
    domain: "backend",
    category: "jobs",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["tenant_admin", "platform_owner"],
    requiredEvidence: ["403_for_tenant_admin", "200_for_owner"],
    affectedModules: ["jobs", "platform-admin"],
    relatedGraphNodes: ["api-jobs-cron", "pa-platform-admin", "td-security-rbac"],
    releaseCritical: true,
    estimatedRuntime: "3m",
    prerequisites: ["tenant admin and owner tokens"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "backend-migrations-parity",
    title: "Migration repo/live parity",
    description: "Repo migrations reconcile with live Supabase history without destructive drift.",
    domain: "backend",
    category: "migrations",
    priority: "p1",
    severity: "high",
    executionType: "audit",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["migration_diff_report"],
    affectedModules: ["supabase", "migrations"],
    relatedGraphNodes: ["db-supabase", "risk-migration-drift", "pa-release-pipeline"],
    releaseCritical: true,
    estimatedRuntime: "10m",
    prerequisites: ["Supabase CLI or MCP read access"],
    outputs: ["audit_report"],
    maturity: "defined",
  }),

  // DATABASE
  t({
    testId: "db-schema-core-tables",
    title: "Core schema presence",
    description: "Required public tables exist: tenants, projects, project_members, project_defects.",
    domain: "database",
    category: "schema",
    priority: "p0",
    severity: "critical",
    executionType: "audit",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["table_list_match"],
    affectedModules: ["supabase", "schema"],
    relatedGraphNodes: ["db-supabase", "pa-projects"],
    releaseCritical: true,
    estimatedRuntime: "5m",
    prerequisites: ["service role read-only audit"],
    outputs: ["schema_inventory"],
    maturity: "defined",
  }),
  t({
    testId: "db-rls-enabled",
    title: "RLS enabled on tenant tables",
    description: "Tenant-scoped tables have RLS enabled and policies present.",
    domain: "database",
    category: "RLS",
    priority: "p0",
    severity: "critical",
    executionType: "audit",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["rls_on", "policy_count"],
    affectedModules: ["supabase", "rls"],
    relatedGraphNodes: ["db-supabase", "pa-tenant-isolation", "td-security-rbac"],
    releaseCritical: true,
    estimatedRuntime: "8m",
    prerequisites: ["pg_catalog read"],
    outputs: ["rls_report"],
    maturity: "defined",
  }),
  t({
    testId: "db-tenant-isolation-negative",
    title: "Tenant isolation negative test",
    description: "User from tenant A cannot read tenant B project rows via anon/authenticated client.",
    domain: "database",
    category: "tenant_isolation",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["zero_cross_tenant_rows"],
    affectedModules: ["rls", "projects"],
    relatedGraphNodes: ["pa-tenant-isolation", "risk-tenant-leakage", "td-security-rbac"],
    releaseCritical: true,
    estimatedRuntime: "6m",
    prerequisites: ["two tenant fixtures"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "db-indexes-hot-paths",
    title: "Hot path index audit",
    description: "Foreign keys and tenant_id filters on high-traffic tables have supporting indexes.",
    domain: "database",
    category: "indexes",
    priority: "p2",
    severity: "medium",
    executionType: "audit",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["index_recommendations"],
    affectedModules: ["supabase", "performance"],
    relatedGraphNodes: ["db-supabase", "td-performance"],
    releaseCritical: false,
    estimatedRuntime: "15m",
    prerequisites: ["EXPLAIN on representative queries"],
    outputs: ["index_audit"],
    maturity: "planned",
  }),

  // SECURITY
  t({
    testId: "sec-rbac-platform-owner-grant",
    title: "Platform owner grant required",
    description: "Platform admin pages and APIs require platform_owner_grants — tenant admin insufficient.",
    domain: "security",
    category: "RBAC",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["web", "api", "staging"],
    supportedRoles: ["tenant_admin", "platform_owner"],
    requiredEvidence: ["403_or_redirect", "owner_200"],
    affectedModules: ["platform-admin", "rbac"],
    relatedGraphNodes: ["pa-platform-admin", "role-platform-owner", "risk-platform-admin-exposure"],
    releaseCritical: true,
    estimatedRuntime: "4m",
    prerequisites: ["tenant admin without grant"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "sec-owner-access-cloudflare",
    title: "Admin host Cloudflare Access",
    description: "admin.aistroyka.ai protected by owner-only Access policy with MFA and no bypass.",
    domain: "security",
    category: "owner_access",
    priority: "p0",
    severity: "critical",
    executionType: "audit",
    supportedPlatforms: ["production", "staging"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["access_policy_audit"],
    affectedModules: ["cloudflare", "platform-admin"],
    relatedGraphNodes: ["pa-platform-admin", "rg-platform-admin-access"],
    releaseCritical: true,
    estimatedRuntime: "5m",
    prerequisites: ["CLOUDFLARE_ACCESS_API_TOKEN or manual audit"],
    outputs: ["audit_report"],
    maturity: "live",
  }),
  t({
    testId: "sec-platform-admin-api-gate",
    title: "Platform admin API gate",
    description: "requirePlatformOwnerApi rejects non-owner on /api/v1/platform/*.",
    domain: "security",
    category: "platform_admin",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["tenant_admin", "platform_owner"],
    requiredEvidence: ["403_unauthorized"],
    affectedModules: ["platform-admin", "api"],
    relatedGraphNodes: ["api-platform-admin", "td-security-rbac"],
    releaseCritical: true,
    estimatedRuntime: "2m",
    prerequisites: ["API test tokens"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "sec-headers-middleware",
    title: "Security headers smoke",
    description: "Middleware applies canonical security headers on HTML and API responses.",
    domain: "security",
    category: "headers",
    priority: "p1",
    severity: "high",
    executionType: "smoke",
    supportedPlatforms: ["web", "staging", "production"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["header_presence"],
    affectedModules: ["middleware", "security-headers"],
    relatedGraphNodes: ["pa-public-website", "td-security-rbac"],
    releaseCritical: true,
    estimatedRuntime: "1m",
    prerequisites: ["scripts/smoke/security_headers.sh"],
    outputs: ["pass_fail"],
    maturity: "live",
  }),
  t({
    testId: "sec-csp-policy",
    title: "Content-Security-Policy audit",
    description: "CSP directives present and do not break dashboard or auth flows.",
    domain: "security",
    category: "CSP",
    priority: "p1",
    severity: "high",
    executionType: "audit",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["csp_header", "console_violations"],
    affectedModules: ["security-headers"],
    relatedGraphNodes: ["pa-web-dashboard", "td-security-rbac"],
    releaseCritical: false,
    estimatedRuntime: "10m",
    prerequisites: ["browser console capture"],
    outputs: ["csp_report"],
    maturity: "planned",
  }),
  t({
    testId: "sec-jwt-session-integrity",
    title: "JWT session integrity",
    description: "Expired or tampered sessions fail closed on protected routes.",
    domain: "security",
    category: "JWT",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "web", "staging"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["401_on_bad_token"],
    affectedModules: ["auth", "middleware"],
    relatedGraphNodes: ["api-auth-session", "risk-auth-broken"],
    releaseCritical: true,
    estimatedRuntime: "3m",
    prerequisites: ["invalid token fixtures"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "sec-secrets-not-in-repo",
    title: "Secrets inventory scan",
    description: "No committed secrets, .env values, or tokens in tracked files.",
    domain: "security",
    category: "secrets",
    priority: "p0",
    severity: "critical",
    executionType: "audit",
    supportedPlatforms: ["web"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["git_secrets_scan_clean"],
    affectedModules: ["repo", "ci"],
    relatedGraphNodes: ["pa-release-pipeline", "td-security-rbac"],
    releaseCritical: true,
    estimatedRuntime: "2m",
    prerequisites: ["local git scan or gitleaks"],
    outputs: ["scan_report"],
    maturity: "defined",
  }),

  // AI
  t({
    testId: "ai-provider-health-live",
    title: "AI live provider gate",
    description: "ai_live_provider.sh --require-live exits 0 with non-fallback response.",
    domain: "ai",
    category: "provider_health",
    priority: "p0",
    severity: "critical",
    executionType: "probe",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["exit_0", "no_x_ai_fallback_reason"],
    affectedModules: ["ai", "copilot"],
    relatedGraphNodes: ["api-ai", "pa-ai-copilot", "rg-ai-live-gate", "td-ai-safety"],
    releaseCritical: true,
    estimatedRuntime: "2m",
    prerequisites: ["AI provider configured on staging"],
    outputs: ["smoke_log"],
    maturity: "live",
  }),
  t({
    testId: "ai-prompt-injection-suite",
    title: "Prompt injection regression",
    description: "Copilot resists instruction override and system prompt exfiltration attempts.",
    domain: "ai",
    category: "prompt_injection",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["injection_blocked", "no_system_leak"],
    affectedModules: ["ai", "copilot"],
    relatedGraphNodes: ["pa-ai-copilot", "td-ai-safety", "risk-ai-leakage"],
    releaseCritical: true,
    estimatedRuntime: "15m",
    prerequisites: ["injection fixture catalog"],
    outputs: ["pass_fail", "response_samples"],
    maturity: "planned",
  }),
  t({
    testId: "ai-hallucination-guardrails",
    title: "Hallucination guardrails",
    description: "Copilot defers or cites when project context is missing — no fabricated site facts.",
    domain: "ai",
    category: "hallucination",
    priority: "p1",
    severity: "high",
    executionType: "manual",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["manager"],
    requiredEvidence: ["response_review"],
    affectedModules: ["ai", "copilot"],
    relatedGraphNodes: ["pa-ai-copilot", "td-ai-safety"],
    releaseCritical: false,
    estimatedRuntime: "20m",
    prerequisites: ["empty project context"],
    outputs: ["manual_rubric"],
    maturity: "planned",
  }),
  t({
    testId: "ai-confidence-scoring",
    title: "AI confidence scoring",
    description: "Engineering intelligence confidence reflects probe evidence — not synthetic scores.",
    domain: "ai",
    category: "confidence",
    priority: "p1",
    severity: "medium",
    executionType: "audit",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["confidence_matches_probes"],
    affectedModules: ["roma", "engineering-intelligence"],
    relatedGraphNodes: ["pa-roma-qa-center", "pa-ai-copilot"],
    releaseCritical: false,
    estimatedRuntime: "5m",
    prerequisites: ["ROMA dashboard access"],
    outputs: ["audit_note"],
    maturity: "defined",
  }),
  t({
    testId: "ai-reasoning-boundary",
    title: "AI reasoning boundary",
    description: "Copilot does not perform unauthorized actions or mutate data without explicit user flow.",
    domain: "ai",
    category: "reasoning",
    priority: "p1",
    severity: "high",
    executionType: "manual",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["manager"],
    requiredEvidence: ["no_side_effect_mutations"],
    affectedModules: ["ai", "copilot"],
    relatedGraphNodes: ["pa-ai-copilot", "td-ai-safety"],
    releaseCritical: false,
    estimatedRuntime: "15m",
    prerequisites: ["copilot enabled tenant"],
    outputs: ["manual_checklist"],
    maturity: "planned",
  }),
  t({
    testId: "ai-memory-isolation",
    title: "AI memory / context isolation",
    description: "Copilot context scoped to tenant/project — no cross-tenant memory bleed.",
    domain: "ai",
    category: "memory",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["tenant_scoped_context"],
    affectedModules: ["ai", "copilot"],
    relatedGraphNodes: ["pa-tenant-isolation", "pa-ai-copilot", "risk-ai-leakage"],
    releaseCritical: true,
    estimatedRuntime: "10m",
    prerequisites: ["two tenant fixtures"],
    outputs: ["pass_fail"],
    maturity: "planned",
  }),

  // MOBILE iOS Manager
  t({
    testId: "ios-manager-login-smoke",
    title: "iOS Manager login smoke",
    description: "Manager app launches, login succeeds, pilot dashboard ids reachable in simulator.",
    domain: "mobile_ios",
    category: "Manager",
    priority: "p0",
    severity: "critical",
    executionType: "smoke",
    supportedPlatforms: ["ios", "staging"],
    supportedRoles: ["manager"],
    requiredEvidence: ["uitest_pass", "login_screen"],
    affectedModules: ["ios-manager"],
    relatedGraphNodes: ["mobile-ios-manager", "pa-manager-review", "td-mobile-ios"],
    releaseCritical: true,
    estimatedRuntime: "8m",
    prerequisites: ["Xcode simulator", "pilot credentials"],
    outputs: ["xcode_test_log"],
    maturity: "partial",
  }),
  t({
    testId: "ios-manager-report-review",
    title: "iOS Manager report review",
    description: "Manager can open pending worker report and approve/reject.",
    domain: "mobile_ios",
    category: "Manager",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["ios", "staging"],
    supportedRoles: ["manager"],
    requiredEvidence: ["approval_state_change"],
    affectedModules: ["ios-manager", "reports"],
    relatedGraphNodes: ["pa-manager-review", "api-reports", "risk-manager-review-broken"],
    releaseCritical: true,
    estimatedRuntime: "12m",
    prerequisites: ["pending report fixture"],
    outputs: ["uitest_log"],
    maturity: "planned",
  }),

  // MOBILE iOS Worker
  t({
    testId: "ios-worker-login-smoke",
    title: "iOS Worker login smoke",
    description: "Worker app launches and authenticates against staging.",
    domain: "mobile_ios",
    category: "Worker",
    priority: "p0",
    severity: "critical",
    executionType: "smoke",
    supportedPlatforms: ["ios", "staging"],
    supportedRoles: ["worker"],
    requiredEvidence: ["uitest_pass"],
    affectedModules: ["ios-worker"],
    relatedGraphNodes: ["mobile-ios-worker", "pa-worker-reports", "td-mobile-ios"],
    releaseCritical: true,
    estimatedRuntime: "8m",
    prerequisites: ["Xcode simulator"],
    outputs: ["xcode_test_log"],
    maturity: "partial",
  }),
  t({
    testId: "ios-worker-report-sync",
    title: "iOS Worker report sync",
    description: "Worker submits report with photo; sync completes with server cursor.",
    domain: "mobile_ios",
    category: "Worker",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["ios", "staging"],
    supportedRoles: ["worker"],
    requiredEvidence: ["sync_200", "server_cursor"],
    affectedModules: ["ios-worker", "reports", "storage"],
    relatedGraphNodes: ["pa-worker-reports", "api-reports", "api-upload-storage", "risk-worker-upload-broken"],
    releaseCritical: true,
    estimatedRuntime: "15m",
    prerequisites: ["Layer B E2E creds optional"],
    outputs: ["e2e_log"],
    maturity: "partial",
  }),

  // MOBILE Android Manager
  t({
    testId: "android-manager-launch",
    title: "Android Manager launch smoke",
    description: "Manager Compose app launches without crash on emulator.",
    domain: "mobile_android",
    category: "Manager",
    priority: "p2",
    severity: "medium",
    executionType: "smoke",
    supportedPlatforms: ["android", "staging"],
    supportedRoles: ["manager"],
    requiredEvidence: ["instrumented_test_pass"],
    affectedModules: ["android-manager"],
    relatedGraphNodes: ["mobile-android-manager", "td-mobile-android"],
    releaseCritical: false,
    estimatedRuntime: "5m",
    prerequisites: ["Android SDK", "emulator"],
    outputs: ["gradle_test_log"],
    maturity: "partial",
  }),

  // MOBILE Android Worker
  t({
    testId: "android-worker-launch",
    title: "Android Worker launch smoke",
    description: "Worker app instrumented launch test passes.",
    domain: "mobile_android",
    category: "Worker",
    priority: "p2",
    severity: "medium",
    executionType: "smoke",
    supportedPlatforms: ["android", "staging"],
    supportedRoles: ["worker"],
    requiredEvidence: ["instrumented_test_pass"],
    affectedModules: ["android-worker"],
    relatedGraphNodes: ["mobile-android-worker", "td-mobile-android"],
    releaseCritical: false,
    estimatedRuntime: "5m",
    prerequisites: ["Android SDK"],
    outputs: ["gradle_test_log"],
    maturity: "partial",
  }),

  // PERFORMANCE
  t({
    testId: "perf-web-cwv-dashboard",
    title: "Dashboard Core Web Vitals",
    description: "LCP, INP, CLS within targets on dashboard entry (staging).",
    domain: "performance",
    category: "web",
    priority: "p2",
    severity: "medium",
    executionType: "probe",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["lighthouse_or_cwv"],
    affectedModules: ["dashboard", "web"],
    relatedGraphNodes: ["pa-web-dashboard", "td-performance"],
    releaseCritical: false,
    estimatedRuntime: "10m",
    prerequisites: ["Lighthouse CI or field data"],
    outputs: ["cwv_scores"],
    maturity: "planned",
  }),
  t({
    testId: "perf-api-health-latency",
    title: "Health API latency",
    description: "p95 latency for /api/v1/health under threshold on staging.",
    domain: "performance",
    category: "api",
    priority: "p2",
    severity: "medium",
    executionType: "probe",
    supportedPlatforms: ["api", "staging"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["p95_ms"],
    affectedModules: ["api"],
    relatedGraphNodes: ["api-health", "td-performance"],
    releaseCritical: false,
    estimatedRuntime: "3m",
    prerequisites: ["repeat curl or k6 light"],
    outputs: ["latency_stats"],
    maturity: "planned",
  }),
  t({
    testId: "perf-mobile-ios-startup",
    title: "iOS cold startup time",
    description: "Worker/Manager cold launch to interactive under target on device/simulator.",
    domain: "performance",
    category: "mobile",
    priority: "p3",
    severity: "low",
    executionType: "manual",
    supportedPlatforms: ["ios"],
    supportedRoles: ["worker", "manager"],
    requiredEvidence: ["startup_ms"],
    affectedModules: ["ios"],
    relatedGraphNodes: ["mobile-ios-worker", "td-performance"],
    releaseCritical: false,
    estimatedRuntime: "20m",
    prerequisites: ["Instruments or manual stopwatch"],
    outputs: ["timing_notes"],
    maturity: "planned",
  }),

  // ACCESSIBILITY
  t({
    testId: "a11y-dashboard-axe",
    title: "Dashboard axe audit",
    description: "Key dashboard routes pass axe-core critical violations check.",
    domain: "accessibility",
    category: "wcag",
    priority: "p2",
    severity: "medium",
    executionType: "automated",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["axe_critical_zero"],
    affectedModules: ["dashboard"],
    relatedGraphNodes: ["pa-web-dashboard", "td-accessibility"],
    releaseCritical: false,
    estimatedRuntime: "8m",
    prerequisites: ["Playwright axe integration"],
    outputs: ["axe_report"],
    maturity: "planned",
  }),

  // UX
  t({
    testId: "ux-onboarding-dashboard",
    title: "Post-login dashboard onboarding",
    description: "New user reaches dashboard onboarding — not forced subscribe when cabinet expected.",
    domain: "ux",
    category: "onboarding",
    priority: "p1",
    severity: "high",
    executionType: "automated",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["tenant_admin"],
    requiredEvidence: ["dashboard_visible", "no_forced_subscribe"],
    affectedModules: ["dashboard", "activation"],
    relatedGraphNodes: ["pa-web-dashboard", "td-web-e2e"],
    releaseCritical: true,
    estimatedRuntime: "5m",
    prerequisites: ["fresh test user"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),

  // VISUAL
  t({
    testId: "visual-public-marketing-ban",
    title: "No banned marketing tokens",
    description: "Public pages exclude MOCK_METRICS, fake counts, and banned demo CTAs.",
    domain: "visual",
    category: "marketing_compliance",
    priority: "p1",
    severity: "high",
    executionType: "automated",
    supportedPlatforms: ["web", "staging", "production"],
    supportedRoles: ["anonymous"],
    requiredEvidence: ["grep_clean", "visual_scan"],
    affectedModules: ["public-site"],
    relatedGraphNodes: ["pa-public-website", "td-visual-design"],
    releaseCritical: true,
    estimatedRuntime: "2m",
    prerequisites: ["rg or ci grep"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),

  // RELEASE
  t({
    testId: "release-staging-buildstamp",
    title: "Staging buildStamp verification",
    description: "Merged main SHA reflected in staging buildStamp within deploy SLA.",
    domain: "release",
    category: "deploy_truth",
    priority: "p0",
    severity: "critical",
    executionType: "probe",
    supportedPlatforms: ["staging"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["buildStamp_matches_merge"],
    affectedModules: ["deploy", "ci"],
    relatedGraphNodes: ["pa-release-pipeline", "rg-staging-deploy", "td-release-smoke"],
    releaseCritical: true,
    estimatedRuntime: "1m",
    prerequisites: ["known merge SHA"],
    outputs: ["health_json"],
    maturity: "live",
  }),
  t({
    testId: "release-production-buildstamp",
    title: "Production buildStamp verification",
    description: "Production deploy SHA verified via health or CI workflow_run chain.",
    domain: "release",
    category: "deploy_truth",
    priority: "p0",
    severity: "critical",
    executionType: "probe",
    supportedPlatforms: ["production"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["buildStamp_sha7"],
    affectedModules: ["deploy"],
    relatedGraphNodes: ["pa-release-pipeline", "rg-production-deploy"],
    releaseCritical: true,
    estimatedRuntime: "1m",
    prerequisites: ["production health reachable"],
    outputs: ["health_json"],
    maturity: "live",
  }),
  t({
    testId: "release-ci-check-green",
    title: "CI check gate",
    description: "PR merge requires passing check workflow: i18n, lint, test, cf:build.",
    domain: "release",
    category: "ci_gate",
    priority: "p0",
    severity: "critical",
    executionType: "audit",
    supportedPlatforms: ["web"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["ci_check_pass"],
    affectedModules: ["ci"],
    relatedGraphNodes: ["pa-release-pipeline", "risk-release-pipeline-broken"],
    releaseCritical: true,
    estimatedRuntime: "—",
    prerequisites: ["GitHub PR checks"],
    outputs: ["ci_status"],
    maturity: "live",
  }),

  // PILOT
  t({
    testId: "pilot-role-smoke-web",
    title: "Pilot role smoke (web)",
    description: "Scoped pilot E2E: login, dashboard, project access for pilot credentials.",
    domain: "pilot",
    category: "role_smoke",
    priority: "p0",
    severity: "critical",
    executionType: "smoke",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["tenant_admin", "manager", "worker"],
    requiredEvidence: ["e2e_pass"],
    affectedModules: ["pilot", "dashboard"],
    relatedGraphNodes: ["pa-web-dashboard", "rg-pilot-smoke", "td-web-e2e"],
    releaseCritical: true,
    estimatedRuntime: "15m",
    prerequisites: ["PILOT_E2E_* secrets or .env.pilot"],
    outputs: ["playwright_report"],
    maturity: "partial",
  }),
  t({
    testId: "pilot-intake-validation",
    title: "Pilot intake card validation",
    description: "validate_pilot_intake.mjs passes for READY intake before Day 0.",
    domain: "pilot",
    category: "intake",
    priority: "p0",
    severity: "high",
    executionType: "audit",
    supportedPlatforms: ["web"],
    supportedRoles: ["platform_owner"],
    requiredEvidence: ["intake_ready_verdict"],
    affectedModules: ["pilot", "launch"],
    relatedGraphNodes: ["pa-release-pipeline"],
    releaseCritical: true,
    estimatedRuntime: "1m",
    prerequisites: ["pilot-intake template filled"],
    outputs: ["validation_report"],
    maturity: "defined",
  }),

  // BUSINESS FLOWS
  t({
    testId: "bf-reports-worker-submit",
    title: "Worker report submit flow",
    description: "End-to-end: worker creates report, uploads media, syncs to server.",
    domain: "business_flow",
    category: "reports",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["ios", "android", "api", "staging"],
    supportedRoles: ["worker"],
    requiredEvidence: ["report_row", "media_object"],
    affectedModules: ["reports", "storage"],
    relatedGraphNodes: ["bf-worker-submit-report", "pa-worker-reports", "api-reports"],
    releaseCritical: true,
    estimatedRuntime: "15m",
    prerequisites: ["worker creds", "project"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "bf-reports-manager-approve",
    title: "Manager report approval flow",
    description: "Manager reviews and approves worker report; status visible to worker.",
    domain: "business_flow",
    category: "approvals",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["web", "ios", "staging"],
    supportedRoles: ["manager", "worker"],
    requiredEvidence: ["status_approved"],
    affectedModules: ["reports"],
    relatedGraphNodes: ["bf-manager-approve-report", "pa-manager-review", "risk-manager-review-broken"],
    releaseCritical: true,
    estimatedRuntime: "12m",
    prerequisites: ["pending report"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "bf-projects-onboarding",
    title: "Project onboarding flow",
    description: "Create project, add members, verify RBAC-scoped access.",
    domain: "business_flow",
    category: "projects",
    priority: "p0",
    severity: "critical",
    executionType: "automated",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["tenant_admin", "manager"],
    requiredEvidence: ["project_created", "member_access"],
    affectedModules: ["projects"],
    relatedGraphNodes: ["bf-project-onboarding", "pa-projects", "api-projects"],
    releaseCritical: true,
    estimatedRuntime: "10m",
    prerequisites: ["tenant admin creds"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "bf-tasks-assignment",
    title: "Task assignment flow",
    description: "Manager assigns task; worker sees assignment in mobile/web.",
    domain: "business_flow",
    category: "tasks",
    priority: "p1",
    severity: "high",
    executionType: "automated",
    supportedPlatforms: ["web", "ios", "staging"],
    supportedRoles: ["manager", "worker"],
    requiredEvidence: ["task_visible_to_worker"],
    affectedModules: ["tasks"],
    relatedGraphNodes: ["pa-tasks"],
    releaseCritical: false,
    estimatedRuntime: "10m",
    prerequisites: ["project with tasks enabled"],
    outputs: ["pass_fail"],
    maturity: "planned",
  }),
  t({
    testId: "bf-notifications-delivery",
    title: "Notification delivery flow",
    description: "In-app or push notification reaches target role after trigger event.",
    domain: "business_flow",
    category: "notifications",
    priority: "p2",
    severity: "medium",
    executionType: "manual",
    supportedPlatforms: ["web", "ios", "android", "staging"],
    supportedRoles: ["worker", "manager"],
    requiredEvidence: ["notification_received"],
    affectedModules: ["notifications"],
    relatedGraphNodes: ["pa-notifications"],
    releaseCritical: false,
    estimatedRuntime: "15m",
    prerequisites: ["FCM/APNs configured"],
    outputs: ["manual_log"],
    maturity: "planned",
  }),
  t({
    testId: "bf-documents-upload-share",
    title: "Document upload and share",
    description: "Upload document to project; authorized roles can download.",
    domain: "business_flow",
    category: "documents",
    priority: "p1",
    severity: "high",
    executionType: "automated",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["tenant_admin", "manager"],
    requiredEvidence: ["document_row", "download_ok"],
    affectedModules: ["documents", "storage"],
    relatedGraphNodes: ["bf-document-upload", "pa-documents", "api-documents"],
    releaseCritical: false,
    estimatedRuntime: "8m",
    prerequisites: ["project fixture"],
    outputs: ["pass_fail"],
    maturity: "defined",
  }),
  t({
    testId: "bf-finance-customer-boundary",
    title: "Customer finance boundary",
    description: "Customer/portal surfaces never expose internal contractor costs or margin.",
    domain: "business_flow",
    category: "finance",
    priority: "p0",
    severity: "critical",
    executionType: "audit",
    supportedPlatforms: ["web", "staging"],
    supportedRoles: ["client", "stakeholder"],
    requiredEvidence: ["no_internal_cost_fields"],
    affectedModules: ["costs", "portal"],
    relatedGraphNodes: ["pa-costs-budgets", "risk-ai-leakage", "td-security-rbac"],
    releaseCritical: true,
    estimatedRuntime: "10m",
    prerequisites: ["stakeholder portal access"],
    outputs: ["audit_report"],
    maturity: "defined",
  }),
];

const ALL_DOMAINS: RomaTestCatalogDomain[] = [
  "web",
  "backend",
  "database",
  "security",
  "ai",
  "mobile_ios",
  "mobile_android",
  "performance",
  "accessibility",
  "ux",
  "visual",
  "release",
  "pilot",
  "business_flow",
];

let cachedCatalog: RomaTestCatalog | null = null;

export function getTestCatalog(): RomaTestCatalog {
  if (cachedCatalog) return cachedCatalog;
  cachedCatalog = {
    version: "v1",
    executionEnabled: false,
    generatedAt: "2026-07-04T00:00:00.000Z",
    items: ITEMS,
  };
  return cachedCatalog;
}

export function getTestsByDomain(domain: RomaTestCatalogDomain): RomaTestCatalogItem[] {
  return getTestCatalog().items.filter((item) => item.domain === domain);
}

export function getTestById(testId: string): RomaTestCatalogItem | undefined {
  return getTestCatalog().items.find((item) => item.testId === testId);
}

export function getTestsForGraphNodes(nodeIds: readonly string[]): RomaTestCatalogItem[] {
  const idSet = new Set(nodeIds);
  return getTestCatalog().items.filter((item) =>
    item.relatedGraphNodes.some((nodeId) => idSet.has(nodeId))
  );
}

export function getReleaseCriticalTests(): RomaTestCatalogItem[] {
  return getTestCatalog().items.filter((item) => item.releaseCritical);
}

export function getTestsForRoles(roles: readonly RomaTestCatalogRole[]): RomaTestCatalogItem[] {
  const roleSet = new Set(roles);
  return getTestCatalog().items.filter((item) =>
    item.supportedRoles.some((role) => roleSet.has(role))
  );
}

export function getTestsForPlatforms(platforms: readonly RomaTestCatalogPlatform[]): RomaTestCatalogItem[] {
  const platformSet = new Set(platforms);
  return getTestCatalog().items.filter((item) =>
    item.supportedPlatforms.some((platform) => platformSet.has(platform))
  );
}

export function getTestsForAffectedAreas(areaIds: readonly string[]): RomaTestCatalogItem[] {
  const areaSet = new Set(areaIds);
  return getTestCatalog().items.filter(
    (item) =>
      item.relatedGraphNodes.some((nodeId) => areaSet.has(nodeId)) ||
      item.affectedModules.some((mod) =>
        [...areaSet].some((areaId) => areaId.includes(mod) || mod.includes(areaId.replace(/^pa-/, "")))
      )
  );
}

export function getCatalogSummary(): RomaTestCatalogSummary {
  const items = getTestCatalog().items;
  const countsByDomain = {} as Record<RomaTestCatalogDomain, number>;
  const countsByPriority = { p0: 0, p1: 0, p2: 0, p3: 0 };
  const countsByMaturity = { planned: 0, defined: 0, partial: 0, live: 0 };

  for (const domain of ALL_DOMAINS) {
    countsByDomain[domain] = 0;
  }

  for (const item of items) {
    countsByDomain[item.domain] += 1;
    countsByPriority[item.priority] += 1;
    countsByMaturity[item.maturity] += 1;
  }

  return {
    total: items.length,
    enabledCount: items.filter((i) => i.enabled).length,
    releaseCriticalCount: items.filter((i) => i.releaseCritical).length,
    countsByDomain,
    countsByPriority,
    countsByMaturity,
  };
}

export const ROMA_TEST_CATALOG_DOMAINS = ALL_DOMAINS;

export type { RomaTestCatalogItem };
