/**
 * Runtime helpers for inventory-driven Playwright audits.
 *
 * Static JSON/CSV is generated by `scripts/audit/generate_button_inventory.mjs` (TypeScript compiler API scan).
 * A richer AST pass with `ts-morph` can be added later without changing consumers: import from this module only.
 */
import fs from "node:fs";
import { inventoryPath } from "./routes";

export type ButtonInventoryEntry = {
  id: string;
  kind: string;
  labelText: string;
  pageRoute: string;
  target: string;
  sourceFile: string;
  line: number;
  notes: string;
  expectedEffect?: string;
  apiEndpointsTouched?: string[];
  selectorPlan?: string;
};

export function loadFullInventory(): ButtonInventoryEntry[] {
  const p = inventoryPath();
  if (!fs.existsSync(p)) return [];
  return JSON.parse(fs.readFileSync(p, "utf8")) as ButtonInventoryEntry[];
}

export function loadActionableCtas(limit = 60): ButtonInventoryEntry[] {
  return loadFullInventory()
    .filter((entry) => entry.id.startsWith("cta."))
    .filter((entry) => entry.pageRoute.startsWith("/{locale}/dashboard") || entry.pageRoute === "dashboard-shared")
    .slice(0, limit);
}
